#!/bin/sh
# scripts/compile_and_stage_cv.sh

# Exit immediately if a command exits with a non-zero status.
set -e

echo "Running pre-commit hook: Compiling CV..."

# 1. Compile the Typst document
typst compile rileycv.typ rileycv.pdf

# Check if compilation succeeded (though set -e should handle this)
if [ $? -ne 0 ]; then
  echo "Typst compilation failed!"
  exit 1
fi

echo "Typst compilation successful. Staging PDF..."

# 2. Stage the potentially updated PDF file
# This ensures the version generated by the hook is included in the commit.
git add rileycv.pdf

echo "rileycv.pdf staged."

# 3. Exit with success
exit 0